<h2>transforms 中去思考</h2>

<p><b style = "color : green"><i>
<br>1.如何去使用transforms
<br>2.为什么需要Tensor数据类型
</i></b></p>

<p><b style = "color : blue"><i>
以下是具体的实现的代码：
</i></b></p>

In [20]:
from torchvision import transforms
from PIL import Image

In [21]:
img_path = "E:/python/DEEP learning/pytorch_catdog/data/train/Cat/0.jpg"
img = Image.open(img_path)
print(type(img))

<class 'PIL.JpegImagePlugin.JpegImageFile'>


In [22]:
tensor_trans = transforms.ToTensor()#创建一个具体的工具，要去实现里边的类
tensor_img = tensor_trans(img)#源代码中是用call实现的
print(tensor_img)

tensor([[[0.7961, 0.7961, 0.8000,  ..., 0.9412, 0.9373, 0.9333],
         [0.7961, 0.7961, 0.8000,  ..., 0.9412, 0.9373, 0.9373],
         [0.7961, 0.7961, 0.8000,  ..., 0.9451, 0.9412, 0.9373],
         ...,
         [0.6000, 0.6000, 0.6000,  ..., 0.0078, 0.0078, 0.0078],
         [0.5961, 0.5961, 0.5961,  ..., 0.0039, 0.0039, 0.0039],
         [0.5922, 0.5922, 0.5961,  ..., 0.0039, 0.0039, 0.0039]],

        [[0.6431, 0.6431, 0.6471,  ..., 0.7882, 0.7843, 0.7804],
         [0.6431, 0.6431, 0.6471,  ..., 0.7882, 0.7843, 0.7843],
         [0.6431, 0.6431, 0.6471,  ..., 0.7922, 0.7882, 0.7843],
         ...,
         [0.4784, 0.4784, 0.4784,  ..., 0.0078, 0.0078, 0.0078],
         [0.4745, 0.4745, 0.4745,  ..., 0.0039, 0.0039, 0.0039],
         [0.4706, 0.4706, 0.4745,  ..., 0.0039, 0.0039, 0.0039]],

        [[0.3412, 0.3412, 0.3451,  ..., 0.4784, 0.4745, 0.4706],
         [0.3412, 0.3412, 0.3451,  ..., 0.4784, 0.4745, 0.4745],
         [0.3412, 0.3412, 0.3451,  ..., 0.4824, 0.4784, 0.

In [23]:
import cv2
opencvtt_img = cv2.imread(img_path)
print(type(opencvtt_img))
print(opencvtt_img)
tensor_img = tensor_trans(img)
print(type(tensor_img))

<class 'numpy.ndarray'>
[[[ 87 164 203]
  [ 87 164 203]
  [ 88 165 204]
  ...
  [122 201 240]
  [121 200 239]
  [120 199 238]]

 [[ 87 164 203]
  [ 87 164 203]
  [ 88 165 204]
  ...
  [122 201 240]
  [121 200 239]
  [121 200 239]]

 [[ 87 164 203]
  [ 87 164 203]
  [ 88 165 204]
  ...
  [123 202 241]
  [122 201 240]
  [121 200 239]]

 ...

 [[ 55 122 153]
  [ 55 122 153]
  [ 55 122 153]
  ...
  [  0   2   2]
  [  0   2   2]
  [  0   2   2]]

 [[ 54 121 152]
  [ 54 121 152]
  [ 54 121 152]
  ...
  [  0   1   1]
  [  0   1   1]
  [  0   1   1]]

 [[ 53 120 151]
  [ 53 120 151]
  [ 54 121 152]
  ...
  [  0   1   1]
  [  0   1   1]
  [  0   1   1]]]
<class 'torch.Tensor'>


<p><b style = "color : green"><i>
tensor数据类型中包含了深度学习中所需要的一切数据，比如反向传播，梯度等
</i></b></p>
<img src="./image/first/t1.png">

<p><b style = "color : green"><i>
在tensorboard中做几个实例
</i></b></p>

In [ ]:
from torch.utils.tensorboard import SummaryWriter
writter = SummaryWriter("logs")
writter.add_image("tnsor_image", tensor_img , 0)
tensor_trans = transforms.Normalize([1,1,1],[1,1,1])#参数分别是均值和方差
tensor_img = tensor_trans(tensor_img)#进行归一化
writter.add_image("tnsor_image", tensor_img , 1)
tensor_trans = transforms.Normalize([2,4,6],[5,3,2])#参数分别是均值和方差
tensor_img = tensor_trans(tensor_img)#进行归一化
writter.add_image("tnsor_image", tensor_img , 2)